/* generated by cppy on 2016-12-14 01:15:06.038966 */

#include <python3.4/Python.h>

namespace MO { namespace MATH { class TimelineNd; template <typename T> class ArithmeticArray; } }

namespace MO {
namespace PYTHON34 {

/* Call this before Py_Initialize() */
bool initialize_module_mo3();

extern "C" {
    /* Timeline forward decl */
    struct Timeline_struct;
    Timeline_struct* create_Timeline();
    void destroy_Timeline(PyObject* self);
    Timeline_struct* copy_Timeline(Timeline_struct* self);
    bool is_Timeline(PyObject* arg);

    /* class 'Timeline' */
    struct Timeline_struct
    {
        PyObject_HEAD
        MATH::TimelineNd* tl;

        void cppy_new();
        void cppy_free();
        void cppy_copy(Timeline_struct* copy);
    };

} // extern "C"

} // namespace PYTHON34
} // namespace MO